
resource "aws_iam_role" "iam_role_lambda_requests" {
  name        = "${var.environment}-iam-role-lambda-requests"
  description = "IAM role for lambda requests"
  # Terraform's "jsonencode" function converts a
  # Terraform expression result to valid JSON syntax.
  assume_role_policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "Statement1",
        "Effect" : "Allow",
        "Principal" : {
          "Service" : "lambda.amazonaws.com"
        },
        "Action" : "sts:AssumeRole"
      }
    ]
  })

  tags = {
    environment = var.environment
    application = "lambda-requests"
  }
}

# log stream names are dynamically generated by AWS and cannot be enumerated in advance; scoped to this single log group only (stricter than AWS's own AWSLambdaBasicExecutionRole managed policy, which uses Resource:"*" across all log groups)
#tfsec:ignore:aws-iam-no-policy-wildcards
resource "aws_iam_role_policy" "iam_role_policy_lambda_requests" {
  name = "${var.environment}-iam-role-policy-lambda-requests"
  role = aws_iam_role.iam_role_lambda_requests.id
  # Terraform's "jsonencode" function converts a
  # Terraform expression result to valid JSON syntax.
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "dynamodb:PutItem",
        ]
        Effect   = "Allow"
        Resource = aws_dynamodb_table.dynamodb.arn
      },
      {
        Action = [
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Effect   = "Allow"
        Resource = "${aws_cloudwatch_log_group.cloudwatch_lambda_requests.arn}:*"
      },
      {
        Action = [
          "kms:GenerateDataKey",
          "kms:Decrypt",
          "kms:DescribeKey"
        ]
        Effect   = "Allow"
        Resource = aws_kms_key.dynamodb_key.arn
      }
    ]
  })
}